apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "registry-creds.fullname" . }}
  labels:
    {{- include "registry-creds.labels" . | nindent 4 }}
stringData:
{{- if .Values.aws }}
  {{- range $key, $value := .Values.aws }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if .Values.docker }}
  {{- range $key, $value := .Values.docker }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if .Values.acr }}
  {{- range $key, $value := .Values.acr }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}

---
{{- if .Values.gcr }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "registry-creds.fullname" . }}-gce
  labels:
    {{- include "registry-creds.labels" . | nindent 4 }}
stringData:
  application_default_credentials.json: {{ .Values.gcr.credentials }}
  gcrurl: {{ .Values.gcr.gcrurl }}
{{- end }}
