apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "registry-creds.serviceAccountName" . }}
  labels:
    {{- include "registry-creds.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
